name: agora_rtm
description: >-
      Flutter wrapper around the Agora Real Time Message SDKs for Android and
      iOS.
version: 1.5.1
homepage: 'https://www.agora.io'
repository: 'https://github.com/AgoraIO/Flutter-RTM'
environment:
      sdk: '>=2.12.0 <3.0.0'
      flutter: '>=1.12.13+hotfix.6'
dependencies:
      flutter:
            sdk: flutter
      flutter_web_plugins:
            sdk: flutter
      plugin_platform_interface: ^2.0.2
dev_dependencies:
      flutter_test:
            sdk: flutter
      flutter_lints: ^2.0.0

flutter:
      plugin:
            platforms:
                  android:
                        package: io.agora.agorartm
                        pluginClass: AgoraRtmPlugin
                  ios:
                        pluginClass: AgoraRtmPlugin
                  web:
                        pluginClass: AgoraRtmPluginStructureWeb
                        fileName: agora_rtm_plugin_web.dart

